# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171101_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否可用'),
        ),
    ]
